/*
 * generated by Xtext 2.36.0
 */
package life.game.validation

import life.game.gameOfLifeDSL.GameOfLifeDSLPackage
import life.game.gameOfLifeDSL.Rule
import org.eclipse.xtext.validation.Check

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class GameOfLifeDSLValidator extends AbstractGameOfLifeDSLValidator {
	
//	public static val INVALID_NAME = 'invalidName'
//
//	@Check
//	def checkGreetingStartsWithCapital(Greeting greeting) {
//		if (!Character.isUpperCase(greeting.name.charAt(0))) {
//			warning('Name should start with a capital', 
//					GameOfLifeDSLPackage.Literals.GREETING__NAME,
//					INVALID_NAME)
//		}
//	}

	@Check
	def checkSensibleNeighbors(Rule rule){
		if (rule.reason.condition.neighbors > 8) {
			error('Neighbor condition can not be larger than 8 since a cell has only 8 neighboring cells', null
//				GameOfLifeDSLPackage.Literals.CONDITION__NEIGHBORS
			)
		}
	}
	
}
