/*
 * generated by Xtext 2.36.0
 */
package life.game


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GameOfLifeDSLStandaloneSetup extends GameOfLifeDSLStandaloneSetupGenerated {

	def static void doSetup() {
		new GameOfLifeDSLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
