/*
 * generated by Xtext 2.36.0
 */
package life.game


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class GameOfLifeDSLRuntimeModule extends AbstractGameOfLifeDSLRuntimeModule {
}
